---
#
#
# Deploys the test version of the system
# 
#

- hosts: "test"
  vars_files:
    - "logins.yml"
  roles:
    - "stages-server"
  tasks:

    - name: "clone l'appli stages dans le repertoire test"
      git:
        repo: "https://github.com/sxpert/stages.git"
        clone: "yes"
        version: "2.0"
        dest: "/srv/webs/stages/{{group_names.0}}"

    - name: "obtenir le nom du dernier fichier de backup de la base de prod"
      find:
        age: "-24h"
        paths: 
          - "/srv/oldbackups/"
      register: "backup"
      become: "yes"
      failed_when: "backup.matched != 1"
  
    - name: "supprimer la bdd de test pour debug"
      postgresql_db:
        name: "{{bdd_name}}"
        state: "absent"
      become: "yes"
      become_user: "postgres"
      when: "debug"

    - name: "créer la bdd de test"
      postgresql_db:
        name: "{{bdd_name}}"
        owner: "{{bdd_owner}}"
        encoding: "utf-8"
        state: "present"
      become: "yes"
      become_user: "postgres"
      register: "bdd_created"

    - debug: "var=backup.files.0.path"

    - name: "charger la bdd de test"
      shell: 
        "zcat {{backup.files.0.path}} | psql -f - {{bdd_name}}"
      become: "yes"
      become_user: "postgres"
      when: "bdd_created.changed"

    - debug: "var=inventory_hostname"
    - debug: "var=group_names.0"

    - name: "génération de la conf apache pour le serveur"
      template:
        src: "apache2.conf"
        dest: "/etc/apache2/sites-available/001-stages-{{group_names.0}}.conf"
      become: "yes"

    - name: "supprimes le lien symbolique inutile"
      file: 
        path: "/etc/apache2/sites-enabled/000-default.conf"
        state: "absent"
      become: "yes"

    - name: "création du lien symbolique"
      file: 
        src: "/etc/apache2/sites-available/001-stages-{{group_names.0}}.conf"
        dest: "/etc/apache2/sites-enabled/001-stages-{{group_names.0}}.conf"
        state: "link"
      become: "yes"


# generate configuration of the app from template
    


